import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "./components/header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <footer className="flex flex-wrap gap-x-52 bg-dark-blue text-white p-4">
          <div className="text-xl font-bold pl-64">LOGO</div>
          <div className="flex flex-col items-left">
            <h2 className="text-lg font-bold underline">Contact</h2>
            <p>Email: <a href="mailto:email@domain.com" className="hover:underline">email@domain.com</a></p>
            <p>Phone: 999-999-9999</p>
          </div>
          <div className="flex flex-col items-left">
            <h2 className="text-lg font-bold underline">Socials</h2>
            <p>Facebook Icon</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
